version: 2.1
jobs:
  build_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm sependencies
          command: |
            npm install --save
  build_docker_test:
    docker: 
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build -t nodewebapp -t anjalisoni12/nodewebapp:latest .
            echno $DOCKER_PASSWORD | docker login -u anjalisoni12 --password-stdin
            docker push anjalisoni12/nodewebapp:latest

workflows:
  build_test:
    jobs:
      - build_tests
      - build_docker_test


